services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: ebook-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - cluster.name=ebook-cluster
      - node.name=ebook-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - ebook-network

  ebook-processor:
    build: .
    depends_on:
      - elasticsearch
    volumes:
      - ./ebooks:/app/ebooks
      - ./src:/app/src
      - .:/app
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - PYTHONPATH=/app
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - ./data/.env
    networks:
      - ebook-network

  lumen:
    build: .
    depends_on:
      - elasticsearch
    volumes:
      - ./ebooks:/app/ebooks
      - ./src:/app/src
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - PYTHONPATH=/app
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - ./data/.env
    entrypoint: ["python3", "/app/lumen.py"]
    networks:
      - ebook-network


volumes:
  elasticsearch_data:
    driver: local

networks:
  ebook-network:
    driver: bridge